import { writeFileSync } from "fs";
import { Parser } from "../src/interpreter/parser";

describe("Wiki Interpreter", () => {
  test("Test Tokenise", () => {
    // const cpuTokens = tokenise(CPU_STRING);
    // const gpuTokens = tokenise(GPU_STRING);
    // writeFileSync("cpu_tokens.json", JSON.stringify(cpuTokens, null, 4));
    // writeFileSync("gpu_tokens.json", JSON.stringify(gpuTokens, null, 4));

    const parsedCpuConent = Parser.createAST(CPU_STRING);
    const parsedGpuConent = Parser.createAST(GPU_STRING);

    writeFileSync("cpu_ast.json", JSON.stringify(parsedCpuConent, null, 4));
    writeFileSync("gpu_ast.json", JSON.stringify(parsedGpuConent, null, 4));
  });
});

// Joined array so its not one long line
const CPU_STRING = [
  "{{Infobox item",
  "|image              =PC CPU.png",
  "|image size         =",
  "|icon               =PC_CPU_Icon.png",
  "|type               =Electronics",
  "|slot               =",
  "|weight             =0.08 kg",
  "|grid               =1x1",
  "|price              =₽12,500",
  "|effect             =Generic loot item",
  "|use time           =",
  "|loot xp            =",
  "|exam xp            =",
  "|mods               =",
  "|node               =573477e124597737dd42e191",
  "|id                 =CPU",
  "}}",
  "",
  "'''{{PAGENAME}}''' (CPU) is an [[Loot|item]] in ''[[Escape from Tarkov]]''.",
  "",
  "==Description==",
  "PC central processing units, in lack of properly working computers, have found their purpose as a construction material for makeshift antenna reflector-type parasites.",
  "",
  "==Quests==",
  '* 3 need to be found [[Found in raid|<font color="red">in raid</font>]] for the quest [[Signal - Part 2]]',
  "",
  "==Location==",
  "* In [[Buried barrel cache]]s",
  "* In [[Dead Scav]]s",
  "* In [[Ground cache]]s",
  "* In [[PC block]]s",
  "* In [[Sport bag]]s",
  "",
  "==Trading==",
  '{|class="wikitable"',
  "|-",
  "![[File:PC CPU Icon.png|frameless|link=PC CPU]] x1<br/>[[PC CPU]]",
  "!<big>→</big>",
  "![[File:Prapor 1 icon.png|frameless|link=Prapor]]<br/>[[Prapor|Prapor LL1]]",
  "!<big>→</big>",
  '![[File:Yarygin MP-443 Grach icon.png|frameless|link=Yarygin MP-443 "Grach" 9x19 pistol]]',
  '[[Yarygin MP-443 "Grach" 9x19 pistol]]',
  "|-",
  "![[File:PC CPU Icon.png|frameless|link=PC CPU]] x3<br/>[[PC CPU]]<br/>+<br/>[[File:CPU Fan Icon.png|frameless|link=CPU fan]] x3<br/>[[CPU fan]]",
  "!<big>→</big>",
  "![[File:Peacekeeper 1 icon.png|frameless|link=Peacekeeper]]<br/>[[Peacekeeper|Peacekeeper LL1]]",
  "!<big>→</big>",
  "![[File:M4standardtrade.png|frameless|link=Colt M4A1 5.56x45 assault rifle]]",
  "[[Colt M4A1 5.56x45 assault rifle]]",
  "|-",
  "![[File:1gphone icon.png|frameless|link=Golden 1GPhone smartphone]] x1<br/>[[Golden 1GPhone smartphone]] <br/> [[File:PC CPU Icon.png|frameless|link=PC CPU]] x1<br/>[[PC CPU]]",
  "!<big>→</big>",
  "![[File:Peacekeeper 4 icon.png|frameless|link=Peacekeeper]]<br/>[[Peacekeeper|Peacekeeper LL4]]",
  "!<big>→</big>",
  "![[File:CryeAirframeChops icon.png|frameless|link=Crye Precision AirFrame Chops]]",
  "[[Crye Precision AirFrame Chops]]",
  "|}",
  "",
  "==Crafting==",
  '{|class="wikitable"',
  "|-",
  "![[File:Manual tool.png|frameless|link=Tech manual]] x1<br/>[[Tech manual]]<br/>+<br/>[[File:Multitool tool.png|frameless|link=Leatherman Multitool]] x1<br/>[[Leatherman Multitool]]<br/>+<br/>[[File:MilitaryCircuitBoardIcon.png|frameless|link=Military circuit board]] x2<br/>[[Military circuit board]]<br/>+<br/>[[File:PC CPU Icon.png|frameless|link=PC CPU]] x2<br/>[[PC CPU]]<br/>+<br/>[[File:Capacitorsicon.png|frameless|link=Capacitors]] x5<br/>[[Capacitors]]",
  "!<big>→</big>",
  "!<big>[[Hideout#Modules|Intelligence Center level 2]]</big><br/>37 h 36 min 40 sec",
  "!<big>→</big>",
  "![[File:Virtex programmable processor Icon.png|frameless|link=Virtex programmable processor]] x1<br/>[[Virtex programmable processor]]",
  "|-",
  "![[File:Manual tool.png|frameless|link=Tech manual]] x1<br/>[[Tech manual]]<br/>+<br/>[[File:Ratchetwrench tool.png|frameless|link=Ratchet wrench]] x1<br/>[[Ratchet wrench]]<br/>+<br/>[[File:Circuit Icon.png|frameless|link=Printed circuit board]] x10<br/>[[Printed circuit board]]<br/>+<br/>[[File:PC CPU Icon.png|frameless|link=PC CPU]] x10<br/>[[PC CPU]]<br/>+<br/>[[File:CPU Fan Icon.png|frameless|link=CPU fan]] x2<br/>[[CPU fan]]<br/>+<br/>[[File:VPXFlashIcon.png|frameless|link=VPX Flash Storage Module]] x3<br/>[[VPX Flash Storage Module]]",
  "!<big>→</big>",
  "!<big>[[Hideout#Modules|Intelligence Center level 3]]</big><br/>96 h 56 min 40 sec",
  "!<big>→</big>",
  "![[File:Graphics Card icon.png|frameless|link=Graphics card]] x1<br/>[[Graphics card]]",
  "|}",
  "",
  "==Trivia==",
  "* [[Easter eggs and References]]: This is a parody of the CPU produced by Intel. ",
  "",
  "{{Navbox barter items}}",
  "[[Category:Electronics]]",
  "",
  "[[de:PC Prozessor]]",
  "[[fr:Processeur d'ordinateur]]",
  "[[ru:Центральный процессор]]",
].join("\n");

const GPU_STRING = [
  "{{Infobox item",
  "|image              =Graphics Card.png",
  "|image size         =",
  "|icon               =Graphics Card icon.png",
  "|icon size          =127x64px",
  "|type               =Electronics",
  "|slot               =",
  "|weight             =0.6 kg",
  "|grid               =2x1",
  "|price              =₽16,500",
  "|effect             =Generic loot item",
  "|use time           =",
  "|loot xp            =",
  "|exam xp            =",
  "|mods               =",
  "|node               =57347ca924597744596b4e71",
  "|id                 =video_card",
  "}}",
  "",
  "'''{{PAGENAME}}''' (GPU) is an [[Loot|item]] in ''[[Escape from Tarkov]]''.",
  "",
  "==Description==",
  "A graphics card is just as good a source of electronic components as anything else - fans, CPUs, IC, etc.",
  "",
  "==Notes==",
  "* Only 4 can be held in your PMC inventory at one time.",
  "",
  "==Quests==",
  '* 3 need to be found [[Found in raid|<font color="red">in raid</font>]] or crafted for the quest [[Farming - Part 4]]',
  "",
  "==Quest rewards==",
  "* 1 can be obtained as a quest reward from [[Chemistry Closet]]",
  "",
  "==Hideout==",
  "Used in the [[Hideout#Bitcoin Farm|Hideout bitcoin farm]] to produce [[physical bitcoin]] faster. For more information see the [[Hideout#Bitcoin Farm|bitcoin miner Hideout section]].",
  "",
  "==Location==",
  "* In [[Buried barrel cache]]s",
  "* In [[Dead Scav]]s",
  "* In [[Ground cache]]s",
  "* In [[PC block]]s",
  "* In [[Sport bag]]s",
  "",
  "===[[Customs]]===",
  "* Under the PC desk in the Green Screen room",
  "*On the dead scav",
  "* On the left grocery shelf in Gas Station",
  "*On the ground in front of the counter in Gas Station",
  "* On the 1st floor sofa in 3-story dorms",
  "* On the table in the unlocked room in Gas Station",
  "* On the floor in the middle of the second room inside of Big Red",
  "* On the floor in 3-story dorm room 314 (Marked Room)",
  "* On the floor in Big Red next to the Fire Can (rare)",
  "",
  "===[[Interchange]]===",
  "* On shelves of electronics stores (Texho, German, Techlight, Rasmussen)",
  "*In the furniture store across from Texho by the PS4",
  "* In the [[EMERCOM medical unit key|Emercom medical unit]]",
  "* On the Tables in TTS medical store across from Emercom",
  "* In the Idea office",
  "* On the tech shelf in the back of Power Station",
  "",
  "===[[Shoreline]]===",
  "* In [[Health Resort east wing room 222 key|East wing room 222]], [[Health Resort east wing room 328 key|East wing room 328]], [[Health Resort west wing room 216 key|West wing room 216]], {{5a13ef7e86f7741290491063}}, [[Health Resort office key with a blue tape|East wing room 110]], West wing room 311 (always open), [[Health Resort west wing room 205 key|West wing room 205]] and [[Health Resort east wing office room 107 key|East wing office 107]]",
  "* On second floor desks of Admin Building",
  "* On the second floor of the weather station, in front of the server bay",
  "* In the East wing storage room",
  "*On counter top in the south most house in village  (Right in front of tank)",
  "",
  "===[[Factory]]===",
  '*In the "pumping station"',
  "*In the bottom blue container outside Gate 3 (Two stacked blue containers)",
  "*On top of one of the yellow cart by pit",
  "*Office hallway shelf",
  "",
  "===[[Woods]]===",
  "*Marked circle",
  "*As spawn next to dead scav at Dead Man`s Place camp",
  "*On floor of buildings in Village",
  "",
  "===[[Reserve]]===",
  "* Can be found on server racks inside multiple buildings",
  "* In the shelves of [[RB-AK key|RB-AK]] on second floor of the black bishop building, north of the helicopter",
  "* In Black Knight on a desk, 3rd room on the left from main entrance",
  "* In [[RB-VO marked key|RB-VO]]",
  "",
  "=== [[The Lab]] ===",
  "* Right side of orange dome, on white boxes next to a white shelf",
  "*Right side of orange dome, on the last white table before the stairs that go up to management office.",
  "",
  "==Trading==",
  '{|class="wikitable"',
  "|-",
  "![[File:Graphics Card icon.png|frameless|link=Graphics card]] x1<br/>[[Graphics card]]<br/>+<br/>[[File:ramicon.png|frameless|link=RAM]] x4<br/>[[RAM]]",
  "!<big>→</big>",
  "![[File:Ragman 4 icon.png|frameless|link=Ragman]]<br/>[[Ragman|Ragman LL4]]",
  "!<big>→</big>",
  "![[File:Vulkan-5 (LShZ-5) heavy helmet icon.png|frameless|link=Vulkan-5 (LShZ-5) bulletproof helmet]]",
  "[[Vulkan-5 (LShZ-5) bulletproof helmet]]",
  "|}",
  "",
  "==Crafting==",
  '{|class="wikitable"',
  "|-",
  "![[File:Manual tool.png|frameless|link=Tech manual]] x1<br/>[[Tech manual]]<br/>+<br/>[[File:Ratchetwrench tool.png|frameless|link=Ratchet wrench]] x1<br/>[[Ratchet wrench]]<br/>+<br/>[[File:Circuit Icon.png|frameless|link=Printed circuit board]] x10<br/>[[Printed circuit board]]<br/>+<br/>[[File:PC CPU Icon.png|frameless|link=PC CPU]] x10<br/>[[PC CPU]]<br/>+<br/>[[File:CPU Fan Icon.png|frameless|link=CPU fan]] x2<br/>[[CPU fan]]<br/>+<br/>[[File:VPXFlashIcon.png|frameless|link=VPX Flash Storage Module]] x3<br/>[[VPX Flash Storage Module]]",
  "!<big>→</big>",
  "!<big>[[Hideout#Modules|Intelligence Center level 3]]</big><br/>96 h 56 min 40 sec",
  "!<big>→</big>",
  "![[File:Graphics Card icon.png|frameless|link=Graphics card]] x1<br/>[[Graphics card]]",
  "|}",
  "",
  "==Trivia== ",
  "It's modeled after an ASUS GeForce® GTX 750 TI performance graphics card (GTX750TI-OC-2GD5)",
  "",
  "{{Navbox barter items}}",
  "",
  "[[Category:Electronics]]",
  "",
  "[[de:Grafikkarte]]",
  "[[fr:Carte graphique]]",
  "[[ru:Видеокарта]]",
].join("\n");
